---
kind: pipeline
type: kubernetes
name: build

steps:
  - name: Test1
    image: busybox
    commands:
    - |
      echo starting conatiner 1
      sleep 15
      echo ending

  - name: Test2
    image: busybox
    commands:
    - |
      echo starting container 2
      sleep 25
      echo ending
    depends_on:
    - Test1

  - name: Test3
    image: busybox
    commands:
    - |
      echo starting
      sleep 10
      echo ending
    depends_on:
    - Test1
    
  - name: Test4
    image: busybox
    commands:
    - |
      echo starting
      sleep 20
      echo ending
    depends_on:
    - Test2
    - Test3
---
kind: signature
hmac: a18b25c7960b3944f646905e2d1d5db25390b2cc8792e989432dc0badc017447

...
