---
kind: pipeline
type: kubernetes
name: build

steps:
  - name: Test1
    image: busybox
    commands:
    - |
      echo starting conatiner 1
      sleep 15
      echo ending

  - name: Test2
    image: busybox
    commands:
    - |
      echo starting container 2
      sleep 25
      echo ending

  - name: Test3
    image: busybox
    commands:
    - |
      echo starting
      sleep 10
      echo ending
    depends_on:
    - Test1
    - Test2
---
kind: signature
hmac: 76cb62f6ee1141a7aaf8b5cc090a2c5003889f9fa3e35a46e8b7e431756670fd

...
